- name: Ensure Podman is installed
  ansible.builtin.import_tasks: install_podman.yml

- name: Connexion to ACR
  ansible.builtin.import_tasks: login.yml

- name: Clone, build and push image from the Angular project including Nginx to ACR
  ansible.builtin.import_tasks: push_app_image.yml

- name: Run application from ACR
  ansible.builtin.import_tasks: run_app.yml
