- name: Clone the Angular project from GitLab
  ansible.builtin.git:
    repo: "https://gitlab.com/cedric69/e-commerce-angular17.git"
    dest: /tmp/e-commerce-angular17

- name: Build Docker image from the Angular project
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/casopractico2/e-commerce-angular17"
    path: /tmp/e-commerce-angular17
    tag: latest
    build_args:
      format: docker
      file: Dockerfile

- name: Push Docker image including the Angular app and the Nginx server to ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/casopractico2/e-commerce-angular17:latest"
    push: yes
    tls_verify: false
