- name: Run application from ACR
  containers.podman.podman_container:
    name: e-commerce-angular17
    image: "{{ acr_login_server }}/e-commerce-angular17:latest"
    state: started
    detach: true
    ports:
      - "80:80"