acr_name: "your-acr-name"
acr_login_server: your_acr_login_server.azurecr.io
acr_username: your_acr_username
acr_password: your_acr_password

container_images:
  - source: your_source_registry
    name: your_image_name
    tag: latest


resource_group_name: "your-resource-group"

azure_tenant_id: "your-tenant-id"
azure_client_id: "your-client-id"
azure_client_secret: "your-client-secret"

image_name: "my-app"
image_tag: "latest"

vm_user: "your-vm-user"
vm_host: "your-vm-ip"

aks_namespace: "my-namespace"
