# === ACR Variables ===
acr_login_server: "{{ lookup('community.general.terraform', 'acr_login_server') }}"
acr_username: "{{ lookup('community.general.terraform', 'acr_username') }}"
acr_password: "{{ lookup('community.general.terraform', 'acr_password') }}"

# === VM Variables ===
vm_public_ip: "{{ lookup('community.general.terraform', 'vm_public_ip_addresses') }}"
vm_user: "adminuser"
vm_private_key_path: "/tmp/terraform_vm_key.pem"

# === AKS Variables ===
aks_cluster_name: "{{ lookup('community.general.terraform', 'aks_cluster_name') }}"
aks_kube_config: "{{ lookup('community.general.terraform', 'aks_kube_config') }}"
