all:
  children:
    acr:
      hosts:
        acr-server:
          ansible_host: "{{ lookup('community.general.terraform', 'acr_login_server') }}"
    vm:
      hosts:
        vm-server:
          ansible_host: "{{ lookup('community.general.terraform', 'vm_public_ip_addresses') }}"
          ansible_user: "adminuser"
          ansible_ssh_private_key_file: "/tmp/terraform_vm_key.pem"
    aks:
      hosts:
        aks-server:
          ansible_host: "{{ lookup('community.general.terraform', 'aks_cluster_name') }}"
