- name: Deploy application from ACR to AKS cluster
  kubernetes.core.k8s:
    state: present
    kubeconfig: /root/.kube/config
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-deployment
        namespace: my-aks-unir
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-todolist-app-unir-CP2
        template:
          metadata:
            labels:
              app: my-todolist-app-unir-CP2
          spec:
            containers:
              - name: my-app
                image: "{{ acr_login_server }}/postgen:casopratico2/my-todolist-app-unir-CP2:latest"
                ports:
                  - containerPort: 80
                volumeMounts:
                  - name: volume-unir
                    mountPath: /app/data
            volumes:
              - name: my-pvc-volume-unir
                persistentVolumeClaim:
                  claimName: my-pvc-cp2
            imagePullSecrets:
              - name: acr-secret