- name: Deploy frontend application
  kubernetes.core.k8s:
    state: present
    kubeconfig: /root/.kube/config
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend-deployment
        namespace: my-aks-unir
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-todo-web
        template:
          metadata:
            labels:
              app: my-todo-web
          spec:
            containers:
              - name: frontend-container
                image: "{{ acr_login_server }}/casopractico2/my-todo-web:latest"
                ports:
                  - containerPort: 80
                env:
                  # - name: REACT_APP_API_BASE_URL
                  #   valueFrom:
                  #     configMapKeyRef:
                  #       name: frontend-config
                  #       key: REACT_APP_API_BASE_URL
                  - name: REACT_APP_API_BASE_URL
                    value: "http://backend-service:8080/api/v1"

- name: Deploy backend application
  kubernetes.core.k8s:
    state: present
    kubeconfig: /root/.kube/config
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend-deployment
        namespace: my-aks-unir
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-todo-api
        template:
          metadata:
            labels:
              app: my-todo-api
          spec:
            containers:
              - name: backend-container
                image: "{{ acr_login_server }}/casopractico2/my-todo-api:latest"
                ports:
                  - containerPort: 8080
                # env:
                #   - name: PORT
                #     valueFrom:
                #       configMapKeyRef:
                #         name: backend-config
                #         key: PORT
                #   - name: APP_BASE_URL
                #     valueFrom:
                #       configMapKeyRef:
                #         name: backend-config
                #         key: APP_BASE_URL                 
                #   - name: MONGO_DB
                #     valueFrom:
                #       secretKeyRef:
                #         name: mongodb-secret-unir
                #         key: MONGO_DB
                env:
                  - name: PORT
                    value: "8080"
                  - name: APP_BASE_URL
                    value: "/api/v1/"
                  - name: MONGO_DB
                    value: "mongodb://admin:adminpassword@mongodb-service-unir:27017/todo-app?retryWrites=true&w=majority"
                    
                  - name: ADMIN_NAME
                    value: "admin"
                  - name: ADMIN_PASSWORD
                    value: "admin123"
                  
                # env :
                #   - name: PORT
                #     value: "8080"
                #   - name: APP_BASE_URL
                #     value: "/api/v1/"
                #   - name: MONGO_DB
                #     value: "mongodb://admin:ced123@mongodb-service-unir:27017/todo-app"
