- name: Create MongoDB service
  kubernetes.core.k8s:
    state: present
    kubeconfig: /root/.kube/config
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: mongodb-service-unir
        namespace: my-aks-unir
      spec:
        ports:
          - protocol: TCP
            port: 27017
            targetPort: 27017
        selector:
          app: mongodb-unir
        type: ClusterIP # for internal access only
