- name: Include secret variables
  ansible.builtin.include_vars:
    # file: /root/dev/unir_universidad/IaC-CP2-UNIR/ansible/inventories/production/all_group_vars_secret.yml
    file: ~/IaC-CP2-UNIR/ansible/inventories/production/all_group_vars_secret.yml

- name: Create a Persistent Volume Claim (PVC)
  ansible.builtin.import_tasks: create_pvc.yml

- name: Expose deployment with a LoadBalancer service
  ansible.builtin.import_tasks: expose_lb_service.yml

- name: Login to Azure Container Registry
  ansible.builtin.import_tasks: login.yml

- name: Deploy MongoDB database
  ansible.builtin.import_tasks: deploy_mongodb.yml

- name: Clone, build and push MERN project image from Gitlab repo to ACR
  ansible.builtin.import_tasks: push_app_image.yml

- name: Deploy application from ACR to AKS cluster
  ansible.builtin.import_tasks: deploy_app.yml
