- name: Include secret variables
  ansible.builtin.include_vars:
    file: /root/dev/unir_universidad/IaC-CP2-UNIR/terraform/inventory_vars_dynamic.yml

- name: Create a namespace
  ansible.builtin.import_tasks: create_namespace.yml

- name: Create a Persistent Volume Claim (PVC)
  ansible.builtin.import_tasks: create_pvc.yml

- name: Login to Azure Container Registry
  ansible.builtin.import_tasks: login.yml

- name: Pull, tag, and push MongoDb image to ACR
  ansible.builtin.import_tasks: create_mongodb_image.yml

- name: Deploy MongoDB database to AKS cluster
  ansible.builtin.import_tasks: deploy_mongodb.yml

- name: Expose MongoDB service
  ansible.builtin.import_tasks: expose_mongodb_service.yml

- name: Clone from Gitlab repo, build and push MERN project images to ACR
  ansible.builtin.import_tasks: create_front_back_images.yml
# - name: Expose deployment with a LoadBalancer service
#   ansible.builtin.import_tasks: expose_lb_service.yml
# - name: Deploy application from ACR to AKS cluster
#   ansible.builtin.import_tasks: deploy_app.yml
